--[[----------------------------------------------------------------------------------------------------------
	overrides: XR COMBAT
------------------------------------------------------------------------------------------------------------]]
local db = db
-------------------------------
local function get_best_enemy(npc)
	return redone_ai_combat.get_combat_enemy(npc)
end

function xr_combat.set_combat_type(npc, actor, t)
	if t == nil then
		return
	end

	local storage = db.storage[npc:id()]
	local best_enemy = get_best_enemy(npc)
	storage.enemy = best_enemy

	local script_combat_type = nil
	if t.combat_type ~= nil then
		script_combat_type = xr_logic.pick_section_from_condlist(actor, npc, t.combat_type.condlist)
		if script_combat_type == "nil" then
			script_combat_type = nil
		end
	end

	storage.script_combat_type = script_combat_type
	t.script_combat_type = script_combat_type
end

-------------------------------------------------------------------------------------
-- EVALUATOR CHECK COMBAT
-- false - engine combat, true - script combat
-------------------------------------------------------------------------------------
function xr_combat.evaluator_check_combat:evaluate()
	if not self.object:alive() then
		return false
	end

	local st = self.st
	if st.enabled and get_best_enemy(self.object) then
		local actor = db.actor
		if not actor then
			return false
		end

		return st.script_combat_type ~= nil
	end

	return false
end

-------------------------------------------------------------------------------------
-- EVALUATOR ENEMY
-------------------------------------------------------------------------------------
function xr_combat.evaluator_enemy:evaluate()
	return get_best_enemy(self.object) ~= nil
end